services:
  alldata-db:
    image: postgres:16
    environment:
      POSTGRES_USER: alldata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: alldata
    volumes:
      - alldata_db:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure

  alldata-web:
    # Use a registry image (recommended). Example:
    # APP_IMAGE=ghcr.io/<github-user-or-org>/<repo>
    # If you built `alldata-web:latest` locally on the server, disable Portainer's "Pull images"
    # for the stack, otherwise Portainer will try to pull `alldata-web` from Docker Hub and fail.
    image: ${APP_IMAGE:-alldata-web}:${APP_IMAGE_TAG:-latest}
    environment:
      APP_NAME: ${APP_NAME:-AltData}
      DATABASE_URL: postgresql+psycopg://alldata:${POSTGRES_PASSWORD}@alldata-db:5432/alldata
      INGEST_SECRET: ${INGEST_SECRET}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:-http://localhost:8000}
      AUTH_DISABLED: ${AUTH_DISABLED:-true}
      APP_PASSWORD: ${APP_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
    ports:
      - "8000:8000"
    depends_on:
      - alldata-db
    networks:
      - internal
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  alldata_db:

networks:
  internal:
